name: Push to Hugging Face on PR merge

on:
  pull_request:
    types: [closed]

jobs:
  push_to_huggingface:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clone Hugging Face repository with token
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git clone https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/SDSC/digiwild
        cd digiwild
        cp -R ../* .
        git add .
        git commit -m "Update from main branch"
        git push origin main
